version: '3.8'

services:
  web-app:
    image: 337405469571.dkr.ecr.ap-southeast-2.amazonaws.com/graduation-app:latest
    container_name: web-app
    ports:
      - "80:5000"
    environment:
      - PROJECT_NAME=Training
    restart: always
